import { Product } from './types';

export const products: Product[] = [
    {
        id: 1,
        title: 'Black women printed tee',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'black-women-printed-tee',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },
    {
        id: 2,
        title: 'Black denim for women',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'black-denim-for-women',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },
    {
        id: 3,
        title: 'Black women printed tee',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'super-sneakers',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },
    {
        id: 4,
        title: 'Black women printed tee',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'toppers',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },
    {
        id: 5,
        title: 'Black women printed tee',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'sneakers',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },
    {
        id: 6,
        title: 'Black women printed tee',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'twisters',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },
    {
        id: 7,
        title: 'Black women printed tee',
        image :['/picture/tshirt-2','/picture/tshirt-1.webp'],
        slug: 'twinkels',
        price: 150,
        discount:0,
        catagory :'tops',
        description : ' Best quality t shirt for women',
        size : ['S','M','L'],
        color: ['S#ffffff','#000000','L#e60000'],
        qty: 1,
    },


]